"""add app permission

Revision ID: 30329b1f0b43
Revises: 2adcbe1f5dfb
Create Date: 2025-06-21 20:18:46.821132

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30329b1f0b43'
down_revision = '2adcbe1f5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_permissions',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('has_permission', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_permission_pkey')
    )
    with op.batch_alter_table('app_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_app_permissions_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_app_permissions_app_id', ['app_id'], unique=False)
        batch_op.create_index('idx_app_permissions_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.String(length=50), server_default=sa.text("'only_me'::character varying"), nullable=False))

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('permission')

    with op.batch_alter_table('app_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_app_permissions_tenant_id')
        batch_op.drop_index('idx_app_permissions_app_id')
        batch_op.drop_index('idx_app_permissions_account_id')

    op.drop_table('app_permissions')
    # ### end Alembic commands ###
